#!/bin/bash

# start capturing radar data, storing it in /mnt/3tb/force_data/TODAY's DATE.sqlite

# ugly hard-wired signal characteristics!

OUTFILE=`date +"force%Y-%m-%dT%H-%M-%S.%3N.sqlite"`

# the decimation parameter -d 0 sets sampling rate (64e6 / (d+1)) and hence range resolution 3.0e8 / (64e6 / (d+1)) / 2
# so d=0 gives 2.34375 metres

# the -n parameter is the number of samples per pulse to capture, so at the above resolution,
# the total range is 1024 * 2.34375 = 2.4 km
#
# the various trigger and azimuth parameters specify the nature of these signals coming from
# the radar, and should not be changed
#
# video gain is set to 0, but can be increased to improve resolution of weak features

/home/radar/capture/capture -T --azimuth-gain 20 --azimuth-thresh-relax 30 --azimuth-thresh-excite 10  --trig-delay 0 --trig-latency 5000 --trigger-gain 20 --trig-thresh-excite 32 --trig-thresh-relax 35  --video-gain 0 -d 0 -n 1024 /mnt/3tb/force_data/$OUTFILE &
