#!/bin/bash
# see the help message below for details

# local interface on subnet to which digdar digitizer is
# attached

LOCALHOST=10.42.0.2

# address of digdar digitizer
DIGDARHOST=10.42.0.56

# transfer port - the port used on local ethernet transfer
# from redpitaya digitizer to this computer
PORT=12345

# sampling rate of the digdar digitizer
SAMPLING_RATE=125.000E6

# set the output directory, if not already
if [[ "$DATADIR" == "" ]]; then
    if [[ -d /media/FORCE_radar_1 ]]; then
        DATADIR=/media/FORCE_radar_1
    elif [[ -d /media/FORCE_radar_2 ]]; then
        DATADIR=/media/FORCE_radar_2
    elif [[ -d /home/radar/data ]]; then
        DATADIR=/home/radar/data
    else
        DATADIR=.
    fi
fi

# filename template
DATE=`date +"%Y-%m-%dT%H-%M-%S.%3N"`
OUTFILE="force_$DATE.sqlite"
LOGFILE="pushlog_$DATE.txt"

# default samples per pulse
NUMSAMP=3000

# default decimation rate (1, 2, 8, ...)
DECIM=1

# default number of pulses in ring buffer
PULSES=4000

# default number of pulses to transfer per chunk
CHUNKSIZE=100

# default removal is none
REMOVE=""

# start capturing radar data

if [[ "$1" == "--help" || "$1" == "-h" ]]; then
    cat <<EOF
capture: start capturing radar data.
(use killcapture to stop capturing)

Call like so:

  capture [-d DECIM] [-n SAMPLES] [-p PULSES] [-c CHUNKSIZE] [-r BEGIN:END]*

where:

  - DECIM is the decimation rate.  With the base clock rate of 125
    MHz,

      DECIM = 1  => range resolution = 1.2 metres
      DECIM = 2  => range resolution = 2.4 metres
      DECIM = 3  => range resolution = 3.6 metres
      DECIM = 4  => range resolution = 4.8 metres
      DECIM = 8  => range resolution = 9.6 metres

    These are the only sensible permitted values, currently.
    Default value: $DECIM

  - SAMPLES is the number of samples to capture per pulse.  When
    multiplied by the range resolution, gives the total range we
    capture out to.  Default value: $NUMSAMP

  - PULSES is how many pulses to allocate in the ring buffer on the
    digitizer.  Default value: $PULSES

  - CHUNKSIZE is the number of pulses to transfer at a time.  This must
    divide evenly into PULSES.  Default value: $CHUNKSIZE.

  - BEGIN:END specify portions of the circle to *not* capture.  BEGIN
    and END are both numbers in [0, 1]

       If BEGIN < END, pulses with azimuth in the range [BEGIN, END]
       are discarded.

       If BEGIN > END, pulse with azimuth in the ranges [0, END] and
       [BEGIN, 1] are discarded.

    i.e. all pulses in the clockwise sector from BEGIN to END are
    excluded

    The default, if no -r options is given, is to save all pulses.
    Multiple -r options are permitted, and a pulse is removed
    (discarded) if it belongs to any of the specified azimuth ranges.

    Note that azimuths 0 and 1 correspond to the same point, namely
    the start of the radar's heading pulse, i.e. when the beam is
    pointing toward the front of the radar unit.

This command starts the following processes:
 - a digitizing process on the local redpitaya / digdar digitizer, which
   must be on the local area network at address $DIGDARHOST

 - a capture process on this computer, which stores captured pulses in a database
   with a filename of the form $DATADIR/$OUTFILE

 - a process to generate and push sweep images to the server at discovery.acadiau.ca

These processes are all stopped by the killcapture script.
The digdar digitizer and this computer commmunicate via a TCP connection on port $PORT.

EOF

    exit 1
fi

# parse parameters, which must be in the order specified

if [[ "$1" == "-d" ]]; then
    DECIM=$2
    shift 2
fi

if [[ "$1" == "-n" ]]; then
    NUMSAMP=$2
    shift 2;
fi

if [[ "$1" == "-p" ]]; then
    PULSES=$2
    shift 2;
fi

if [[ "$1" == "-c" ]]; then
    CHUNKSIZE=$2
    shift 2;
fi

if (( $PULSES % $CHUNKSIZE != 0 )); then
    echo "Error: CHUNKSIZE must divide evenly into PULSES"
    exit 1
fi

while [[ "$1" != "" ]]; do
    if [[ "$1" == "-r" ]]; then
        REMOVE="$REMOVE $1 $2"
        shift 2;
    else
        echo "Error: invalid argument: $1.\n  Do capture -h for help."
        exit 1
    fi
done

if (( $DECIM <= 4 )); then
    USE_SUM=--sum
else
    USE_SUM=""
fi

# Listen on port PORT for raw pulse data from the redpitaya digitizer, and pipe this into
# the capture process.  "-d" means don't hang up on no stdin, which is required for running
# netcat in background as a pure listener

killall netcat
( netcat -d -l $PORT | /home/radar/capture/rpcapture -d $DECIM -n $NUMSAMP -T $DATADIR/$OUTFILE) &

sleep 1

# start generating and pushing live images
/home/radar/capture/pushLiveImages.R --samples $NUMSAMP --sampling_rate 125e6 --decim $DECIM > $DATADIR/$LOGFILE 2>&1 &

# start the digdar digitizing process on the redpitaya
ssh -f -n root@$DIGDARHOST "(/opt/bin/digdar -d $DECIM -n $NUMSAMP -p $PULSES -c $CHUNKSIZE $USE_SUM $REMOVE | /opt/bin/netcat $LOCALHOST $PORT)&"
